version: "3.8"

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    networks:
      - cloudsell-network
    env_file:
      - .env
    ports:
      - "8888:8000"

networks:
  cloudsell-network:
    external: true