"""users_wallets

Revision ID: 987a17dc9613
Revises: 13b7df59a5d9
Create Date: 2024-12-24 20:37:19.988654

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "987a17dc9613"
down_revision: Union[str, None] = "13b7df59a5d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("wallet_id", sa.UUID()))
    op.create_foreign_key(None, "users", "wallets", ["wallet_id"], ["id"])
    op.drop_index("ix_wallets_user_id", table_name="wallets")
    op.drop_constraint("wallets_user_id_fkey", "wallets", type_="foreignkey")
    op.drop_column("wallets", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wallets",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "wallets_user_id_fkey", "wallets", "users", ["user_id"], ["id"]
    )
    op.create_index("ix_wallets_user_id", "wallets", ["user_id"], unique=False)
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "wallet_id")
    # ### end Alembic commands ###
